# This is a basic workflow to help you get started with Actions

name: test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: ls
        run: ls -al

      # Runs a set of commands using the runners shell
      - name: echo
        run: echo "This is Checkout"

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      
      - name: chmod gradle
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build --no-daemon
        
      - name: check build
        run: ls ./build/libs
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: docker build
        run: |
          cp ./build/libs/*.war ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_lastest ./Dockerfile
          docker images
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_lastest

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: test
          location: us-central1-c
          project_id: sturdy-cable-343109
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: was-deploy-restart
        run: kubectl rollout restart deployment/was

      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v0.9.0
        with:
          credentials: ${{ secrets.GCP_CS_KEY }}
          path: ./build/libs/*.war
          destination: gs://aiden103/backup.war


